[package]
name = "wasmi-witness"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmi            = { workspace = true }
num-bigint       = { workspace = true }
ark-bn254        = { workspace = true }
ark-ec           = { version = "0.4", default-features = false }
ark-ff           = { version = "0.4", default-features = false }
ark-std          = { workspace = true }
thiserror        = { workspace = true }
bytemuck         = "1"
num-traits       = "0.2"