[package]
name = "laniakea-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
laniakea-core = { path = "../laniakea-core" }
anyhow        = { workspace = true }
serde_json    = { workspace = true }
num-bigint    = { workspace = true }
ark-circom    = { workspace = true }
ark-serialize = { workspace = true }
ark-bn254     = { workspace = true }
ark-groth16   = { workspace = true }
ark-snark     = { workspace = true }
ark-std       = { workspace = true }
rand          = { workspace = true }